config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :faculties
  resources :study_programs
  resources :percentage_assessments
  resources :rank_of_lecturers
  resources :lecturers do
    post :activate,   on: :member
    post :deactivate, on: :member
  end
  resources :assessment_ranges do
    post :activate,   on: :member
    post :deactivate, on: :member
  end
  resources :assessment_results do
    post :confirm,  on: :member
    post :revise,   on: :member
    post :cancel,   on: :member
    post :complete, on: :member
    post :create_list_of_ratings_execution_of_work, on: :member
  end
  resources :assessors do
    post :activate,   on: :member
    post :deactivate, on: :member
  end
  resources :list_of_ratings_execution_of_works do
    get :export_pdf, on: :member
    post :confirm,  on: :member
    post :revise,   on: :member
    post :cancel,   on: :member
    post :complete, on: :member
  end
  resources :preferments do
    post :confirm,  on: :member
    post :revise,   on: :member
    post :cancel,   on: :member
    post :complete, on: :member
  end
  resources :periodic_preferments do
    get :export_pdf, on: :member
    post :confirm,  on: :member
    post :revise,   on: :member
    post :cancel,   on: :member
    post :complete, on: :member
  end

end

app/models/preferment.rb
class Preferment < ActiveRecord::Base
  include DefaultStateTransitions

  after_initialize :set_default_values, if: :new_record?

  def set_default_values
    self.code = SecureRandom.uuid
  end

  belongs_to :list_of_ratings_execution_of_work
  belongs_to :rank_of_lecturer
  belongs_to :current_rank_of_lecturer, class_name: "RankOfLecturer"

  validates :list_of_ratings_execution_of_work_id, presence: true,
                                                   inclusion: { in: proc { ListOfRatingsExecutionOfWork.completed.pluck(:id) }}
  validates :rank_of_lecturer_id,                  presence: true
  validates :current_rank_of_lecturer_id,          presence: true
  validates :decision_letter_number,               presence: true
  validates :submissions_preferment_date,          presence: true,
                                                   timeliness: { type: :date }
  validates :preferment_date,                      presence: true,
                                                   timeliness: { after: :submissions_preferment_date, type: :date}

  scope :completed, -> { where(state: 'completed') }
end

app/controllers/preferments_controller.rb
class PrefermentsController < ApplicationController
  include DefaultStateTransitionCallback

  before_filter :authenticate_user!, :set_page_title

  def index
    @object = Preferment.order(updated_at: :desc).page(params[:page]).per(10)
    generate_index_data_for @object
    set_breadcrumb_for_index
  end

  def show
    @object = find_by_and_decorate(params[:id])
    set_breadcrumb_for_show(@object)
  end

  def new
    @object = Preferment.new
    set_breadcrum_for_new
  end

  def create
    @object = Preferment.new(preferment_params)
    set_breadcrum_for_new

    action = Preferment::Action::Save.new(preferment: @object)
    action.run ? redirect_to(@object) : render('new')
  end

  def edit
    @object = find_by_and_decorate(params[:id])
    edit_callback_for @object
    set_breadcrumb_for_edit @object
  end

  def update
    @object = find_by_and_decorate(params[:id])
    update_callback_for @object, preferment_params
    set_breadcrumb_for_edit @object
  end

  def destroy
    @object = find_by_and_decorate(params[:id])
    destroy_callback_for @object
  end

  def confirm
    @object = find_by_and_decorate(params[:id])
    confirm_callback_for @object
  end

  def revise
    @object = find_by_and_decorate(params[:id])
    revise_callback_for @object
  end

  def cancel
    @object = find_by_and_decorate(params[:id])
    cancel_callback_for @object
  end

  def complete
    @object = find_by_and_decorate(params[:id])
    complete_callback_for @object
  end

private

  def find_by_and_decorate(id)
    decorate Preferment.find(id)
  end

  def preferment_params
    params.require(:preferment)
          .permit(
            :list_of_ratings_execution_of_work_id,
            :rank_of_lecturer_id,
            :decision_letter_number,
            :submissions_preferment_date,
            :preferment_date
          )
  end

  def set_page_title
    @page_title ||= 'Kenaikan Pangkat'
  end

  def set_breadcrumb_for_index
    add_breadcrumb @page_title, preferments_url
  end

  def set_breadcrumb_for_show(object)
    set_breadcrumb_for_index
    add_breadcrumb object.decision_letter_number, preferment_url(object)
  end

  def set_breadcrum_for_new
    set_breadcrumb_for_index
    add_breadcrumb "Buat Baru", new_faculty_url
  end

  def set_breadcrumb_for_edit(object)
    set_breadcrumb_for_show(object)
    add_breadcrumb "Perbaharui", edit_preferment_url(object)
  end
end

app/views/preferments/_form.html.erb
<%= form_for(object, html: { class: "form-horizontal form-label-left"}) do |f| %>
  <div class="box-body">
    <div class="form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12">
        DP3
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.collection_select(
              :list_of_ratings_execution_of_work_id,
              ListOfRatingsExecutionOfWork.completed, :id, :id,
              { include_blank: true },
              { class: "form-control #{error_class(object, :list_of_ratings_execution_of_work_id)}" }
            ) %>
        <%= error_messages(object, :list_of_ratings_execution_of_work_id) %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12">
        Pangat Baru
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.collection_select(
              :rank_of_lecturer_id,
              RankOfLecturer.all, :id, :name,
              { include_blank: true },
              { class: "form-control #{error_class(object, :rank_of_lecturer_id)}" })
            %>
        <%= error_messages(object, :rank_of_lecturer_id) %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12">
        No SK Kenaikan Pangkat
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :decision_letter_number, class: "form-control #{error_class(object, :decision_letter_number)}" %>
        <%= error_messages(object, :decision_letter_number) %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12">
        Tanggal Pengajuan Kenaikan Pangat
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.date_field :submissions_preferment_date, class: "form-control #{error_class(object, :submissions_preferment_date)}" %>
        <%= error_messages(object, :submissions_preferment_date) %>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-3 col-sm-3 col-xs-12">
        Tanggal Kenaikan Pangat
      </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.date_field :preferment_date, class: "form-control #{error_class(object, :preferment_date)}" %>
        <%= error_messages(object, :preferment_date) %>
      </div>
    </div>
  </div>

  <div class="ln_solid"></div>
  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
    <%= f.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/preferments/edit.html.erb
<%= render "layouts/default_edit", resource_title: 'Kenaikan Pangkat' ,object: @object %>

app/views/preferments/index.html.erb
<%= render "layouts/default_index", title: 'Kenaikan Pangkat',
                                    object: @object,
                                    index_data: @index_data,
                                    decorated_object: Preferment.new.decorate %>

app/views/preferments/new.html.erb
<%= render "layouts/default_new", resource_title: 'Kenaikan Pangkat' ,object: @object %>

app/views/preferments/show.html.erb
<%= render "layouts/default_show", title: 'Kenaikan Pangkat' ,object: @object %>
<!-- <div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
          <h3 class="box-title">Detail Kenaikan Pangkat</h3>
      </div>

      <div class="margin">
        <%#= link_to "Buat Baru", new_preferment_path, class: "btn btn-primary btn-sm"%>
        <%#= link_to "Perbaharui", edit_preferment_path(@object), class: "btn btn-warning btn-sm" %>
        <%#= link_to 'Hapus',  @object,  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
      </div>

      <div class="box-body">
        <div class="form-group">
          <label>DP3</label>
          <p class="help-block"><%#= @object.list_of_ratings_execution_of_work_id %></p>
        </div>
        <div class="form-group">
          <label>Pangkat Baru</label>
          <p class="help-block"><%#= @object.rank_of_lecturer_id %></p>
        </div>
        <div class="form-group">
          <label>Masa Kerja</label>
          <p class="help-block"><%#= "#{@object.year_work_period} Tahun, #{@object.month_work_period} Bulan, #{@object.day_work_period} Hari" %></p>
        </div>
        <div class="form-group">
          <label>No SK Kenaikan Pangkat</label>
          <p class="help-block"><%#= @object.decision_letter_number %></p>
        </div>
        <div class="form-group">
          <label>Tanggal Pengajuan Kenaikan Pangkat</label>
          <p class="help-block"><%#= @object.submissions_preferment_date %></p>
        </div>
        <div class="form-group">
          <label>Tanggal Kenaikan Pangkat</label>
          <p class="help-block"><%#= @object.preferment_date %></p>
        </div>
        <div class="form-group">
          <label>Tanggal Dibuat</label>
          <p class="help-block"><%#= @object.created_at.to_formatted_s(:long) %></p>
        </div>
        <div class="form-group">
          <label>Tanggal Diperbaharui</label>
          <p class="help-block"><%#= @object.updated_at.to_formatted_s(:long) %></p>
        </div>
      </div>

    </div>
  </div>
</div>
 -->